services:
    web:
      build: .
      stdin_open: true
      tty: true
      command: bash -c "rails db:migrate && rails assets:precompile && rails s -p 3000 -b '0.0.0.0'"
      environment: 
        TZ: America/Salvador
      volumes:
        - .:/home/app/web
      ports:
        - '3000:3000'